name:                monoids-in-the-categoy-of-endofunctors
version:             0.1.0.0
github:              "jamestmartin/monoids-in-the-categoy-of-endofunctors"
license:             GPL-3.0-or-later
author:              "James Martin"
maintainer:          "james@jtmar.me"
copyright:           "Copyright: (C) 2020 James Martin"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jamestmartin/monoids-in-the-categoy-of-endofunctors#readme>

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators
- Safe

ghc-options:
- -Weverything
#- -Werror
- -Wno-missing-export-lists
- -Wno-missing-import-lists

dependencies:
- base >= 4.13 && < 5
- invariant >= 0.5 && < 0.6
- profunctors >= 5.5 && < 6

library:
  source-dirs: src
