name:                monoids-in-the-category-of-endofunctors
version:             0.1.0.0
github:              "jamestmartin/monoids-in-the-categoy-of-endofunctors"
license:             GPL-3.0-or-later
author:              "James Martin"
maintainer:          "james@jtmar.me"
copyright:           "Copyright: (C) 2020 James Martin"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jamestmartin/monoids-in-the-categoy-of-endofunctors#readme>

default-extensions:
- BlockArguments
- ConstraintKinds
- DataKinds
- DefaultSignatures
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NoImplicitPrelude
- PolyKinds
- QuantifiedConstraints
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

ghc-options:
- -Weverything
#- -Werror
- -Wno-missing-export-lists
- -Wno-missing-import-lists
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-unsafe

dependencies:
- base >= 4.13 && < 5
- template-haskell >= 2.16 && < 3

library:
  source-dirs: src
