name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install Haskell toolchain
      uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.0.1'
        cabal-version: '3.4.0.0'

    - name: Build
      run: cabal v2-build
